**numpy**

In [14]:
import numpy as np
pyhton_list = [1,2,3,4,5]
print (pyhton_list)
numpy_array = np.array([[1,2,3,4,5],[4,5,6,7,8],[3,4,5,6,7,]])
print(numpy_array)

[1, 2, 3, 4, 5]
[[1 2 3 4 5]
 [4 5 6 7 8]
 [3 4 5 6 7]]


creating array from pyhton list

In [6]:
import numpy as np
arr = np.array([1.0,2,3,4])
print (arr)
print (arr.dtype)

[1. 2. 3. 4.]
float64


**numpy array wiht defaut value**
note:defaut value can be 0 or 1



In [ ]:
import numpy as np
arr = np.zeros(3)
print (arr)

[0. 0. 0.]


In [ ]:
note dimension can be different

In [9]:
import numpy as np
arr = np.ones((3,2))
print (arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


**filling arrays with specific value**


In [ ]:
import numpy as np
arr = np.full((3),7)
print (arr)

[7 7 7]


In [ ]:
import numpy as np
arr = np.full((3,3),4)
print (arr)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


**creating sequence of number in numpy**


In [ ]:
import numpy as np
arr = np.arange(1,10,2)
#np.arange(start,stop,step)
print(arr)

[1 3 5 7 9]


In [ ]:
import numpy as np
arr = np.arange(20)
#np.arange(start,stop,step)
#we can also give the range also
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


**creating identity matrices**

In [ ]:
import numpy as np
matrix = np.eye(3)
print (matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**properties of numpy**

shape

In [ ]:
import numpy as np
arr_2d = np.array([[2,3],
                   [5,6]])
print(arr_2d.shape)
#used to print the shape of the array


(2, 2)


size

In [ ]:
import numpy as np
arr_2d = np.array([[2,3],
                   [5,6]])
print(arr_2d.size)

4


.ndim (number of dimension )

In [ ]:
import numpy as np
arr_2d = np.array([[2,3],
                   [5,6]])
print(arr_2d.ndim)

2


.dtype (change the datatype) .

In [ ]:
arr = np.array([1.2,1.4,1.5])
print (arr.dtype)#this tells data type of the array
int_arr = arr.astype(int)# it convert the data type
print (int_arr)
print (int_arr.dtype)


float64
[1 1 1]
int64


**numpy operator**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print (arr + 5)
print (arr - 2)
print (arr * 2)
print (arr / 2)
print (arr ** 2)

[ 6  7  8  9 10]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


**agregation function**

np.sum(array)--add all
np.mean(array)--averange
np.min(array)--min
np.max(array)--maxium
np.std(array)--standard daviation
np.var(array)--variants


In [ ]:
import numpy as np
array = np.array([10,20,30,40,50])
print(np.sum(array))
print(np.mean(array))
print(np.min(array))
print(np.max(array))
print(np.std(array))
print(np.var(array))

150
30.0
10
50
14.142135623730951
200.0


**indexing slicing**

acces elemnt

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print (arr[0])
print (arr[4])
print (arr[-1])

1
5
6


slicing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print (arr[1:3])
print (arr[::-1])#reverse of the array
print (arr[::2])#print the nest second elelmet
print (arr[:4])

[2 3]
[6 5 4 3 2 1]
[1 3 5]
[1 2 3 4]


fancy indexing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print (arr[[0,2,4]])#provides the each index vslues


[1 3 5]


**filtering**(ccondition checking)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print (arr[arr>5])

[6]


**reshaping and manipulating**

syntax- reshape(rows,coloumns)

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
reshape_shape = arr.reshape(2,3)
print (reshape_shape)


[[1 2 3]
 [4 5 6]]


**flattening array**

In [ ]:
**flattening array**

.revel()-- return view(modifies original array )
.flatten()-- copy (doesnot modifies original array )

In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print (arr.flatten())
print (arr.ravel())
#flattering means covert multiple dimension array into single dimension array

[1 2 3 4 5 6]
[1 2 3 4 5 6]


**array modification**

add/insert

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5])
new_arr = np.insert(arr,2,10,)
print (new_arr)
#

[ 1  2 10  3  4  5]


insert in 2d array


In [1]:
import numpy as np

arr = np.array([[1,2],
                [3,4]])
new_arr = np.insert(arr, 1, [10,11], axis=0)

print(new_arr)

[[ 1  2]
 [10 11]
 [ 3  4]]


**append**

In [13]:
import numpy as np
arr = np.array([1,2,3,4])
new_arr = np.append(arr,5)
print (new_arr)

[1 2 3 4 5]


In [14]:
import numpy as np
arr = np.array([1,2,3,4])
new_arr = np.append(arr,[6,7,8])
print (new_arr)

[1 2 3 4 6 7 8]


**cocatination**

In [15]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.concatenate((arr1,arr2))
print (new_arr)

[1 2 3 4 5 6]


**delet

In [19]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.delete(arr,0)#(name of the array , index)
print(arr1)

[2 3 4 5]


In [20]:
import numpy as np
arr = np.array([[1,2],[3,4]])
new_arr = np.delete(arr,1,axis=1)
print (new_arr)
#

[[1]
 [3]]


**stacking (merge)**

In [22]:
#vstack - vertical
#hstck - horizonal
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print (np.vstack((arr1,arr2)))
print (np.hstack((arr1,arr2)))
#

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**spliting**

In [26]:
#np.plit()
#np.hsplit()
#np.vsplite()
import numpy as np
arr = np.array([[1,2],[3,4]])
print(np.split(arr,2))
print(np.hsplit(arr,2))



[array([[1, 2]]), array([[3, 4]])]
[array([[1],
       [3]]), array([[2],
       [4]])]


**bordcasting**

In [27]:
import numpy as np
prices = np.array([100,200,300])
discount =10
final_price = prices -(prices*discount/100)
print (final_price)

[ 90. 180. 270.]


**vectorization**

In [28]:
#performing a operatin in complete aray in fast way
import numpy as np
arr = np.array([1,2,3,4])
multiplied = arr*3
print(multiplied)


[ 3  6  9 12]


**handling missing value**

In [ ]:
# np.isnan - detect missing value
# np.nan_to_num() - replace the missin value with different number
# np.isinf() - detect the infinite value



detect missing value

In [1]:
import numpy as np
arr = np.array([1,2,np.nan,4])
print(np.isnan(arr))

[False False  True False]


replace nan value


In [3]:
import numpy as np
arr = np.array([1,2,np.nan,4])
cleaned = (np.nan_to_num(arr,nan=100))
print (cleaned)

[  1.   2. 100.   4.]


handling infinity value

In [8]:
import numpy as np
arr = np.array([1,2,3,np.nan,np.inf,-np.inf])
cleaned = np.nan_to_num(arr,nan=9, posinf=6,neginf=8)
print(cleaned)

#nan for - null value
#poinf for - positive infinite value
#neginf for - negative infinite value
#for the handling the infinite vlaue syntax - np.nan_to_num(name_the_arr, nan=  )

[1. 2. 3. 9. 6. 8.]
